//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAttendanceConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> manager_id { get; set; }
        public string LeaveType { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
